// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace com.interactiverobert.prototypes.movieexplorer.apple
{
	public partial class MovieDetailViewController : UIViewController
	{
		public MovieDetailViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
