// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace com.interactiverobert.prototypes.movieexplorer.shared.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedConstants {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedConstants() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("com.interactiverobert.prototypes.movieexplorer.shared.Resources.SharedConstants", typeof(SharedConstants).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        public static string GetTopRatedMoviesUriFormatString {
            get {
                return ResourceManager.GetString("GetTopRatedMoviesUriFormatString", resourceCulture);
            }
        }
        
        public static string GetPopularMoviesUriFormatString {
            get {
                return ResourceManager.GetString("GetPopularMoviesUriFormatString", resourceCulture);
            }
        }
        
        public static string GetNowPlayingMoviesUriFormatString {
            get {
                return ResourceManager.GetString("GetNowPlayingMoviesUriFormatString", resourceCulture);
            }
        }
        
        public static string GetUpcomingMoviesUriFormatString {
            get {
                return ResourceManager.GetString("GetUpcomingMoviesUriFormatString", resourceCulture);
            }
        }
        
        public static string GetConfigurationUriFormatString {
            get {
                return ResourceManager.GetString("GetConfigurationUriFormatString", resourceCulture);
            }
        }
        
        public static string GetVidesoForMovieUriFormatString {
            get {
                return ResourceManager.GetString("GetVidesoForMovieUriFormatString", resourceCulture);
            }
        }
        
        public static string GetSimilarForMovieUriFormatString {
            get {
                return ResourceManager.GetString("GetSimilarForMovieUriFormatString", resourceCulture);
            }
        }
        
        public static string OpenInYouTubeFormatString {
            get {
                return ResourceManager.GetString("OpenInYouTubeFormatString", resourceCulture);
            }
        }
        
        public static string SerializedFileExtension {
            get {
                return ResourceManager.GetString("SerializedFileExtension", resourceCulture);
            }
        }
        
        public static string FavoritesCacheKey {
            get {
                return ResourceManager.GetString("FavoritesCacheKey", resourceCulture);
            }
        }
        
        public static string SaveToFavoritesText {
            get {
                return ResourceManager.GetString("SaveToFavoritesText", resourceCulture);
            }
        }
        
        public static string RemoveFromFavoritesText {
            get {
                return ResourceManager.GetString("RemoveFromFavoritesText", resourceCulture);
            }
        }
    }
}
