//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.interactiverobert.prototypes.movieexplorer.shared {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.interactiverobert.prototypes.movieexplorer.shared.StringResources", typeof(StringResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 727d8ece7a1e09019fa1ffdb43d7577b.
        /// </summary>
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string FavoritesCacheKey {
            get {
                return ResourceManager.GetString("FavoritesCacheKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configuration?api_key={0}.
        /// </summary>
        public static string GetConfigurationUriFormatString {
            get {
                return ResourceManager.GetString("GetConfigurationUriFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to movie/now_playing?api_key={0}.
        /// </summary>
        public static string GetNowPlayingMoviesUriFormatString {
            get {
                return ResourceManager.GetString("GetNowPlayingMoviesUriFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to movie/popular?api_key={0}.
        /// </summary>
        public static string GetPopularMoviesUriFormatString {
            get {
                return ResourceManager.GetString("GetPopularMoviesUriFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to movie/{0}/similar?api_key={1}.
        /// </summary>
        public static string GetSimilarForMovieUriFormatString {
            get {
                return ResourceManager.GetString("GetSimilarForMovieUriFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to movie/top_rated?api_key={0}.
        /// </summary>
        public static string GetTopRatedMoviesUriFormatString {
            get {
                return ResourceManager.GetString("GetTopRatedMoviesUriFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to movie/upcoming?api_key={0}.
        /// </summary>
        public static string GetUpcomingMoviesUriFormatString {
            get {
                return ResourceManager.GetString("GetUpcomingMoviesUriFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to movie/{0}/videos?api_key={1}.
        /// </summary>
        public static string GetVidesoForMovieUriFormatString {
            get {
                return ResourceManager.GetString("GetVidesoForMovieUriFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com/watch?v={0}.
        /// </summary>
        public static string OpenInYouTubeFormatString {
            get {
                return ResourceManager.GetString("OpenInYouTubeFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .json.
        /// </summary>
        public static string SerializedFileExtension {
            get {
                return ResourceManager.GetString("SerializedFileExtension", resourceCulture);
            }
        }
    }
}
